# Generated by Django 4.2.7 on 2023-12-05 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 11, 58, 39, 408720, tzinfo=datetime.timezone.utc)),
        ),
    ]
