# Generated by Django 4.2.7 on 2023-11-28 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 20, 41, 9, 910854, tzinfo=datetime.timezone.utc)),
        ),
    ]
