# Generated by Django 4.2.7 on 2023-11-28 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_blog', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 21, 5, 5, 640141, tzinfo=datetime.timezone.utc)),
        ),
    ]
