# Generated by Django 4.2.7 on 2023-12-04 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_blog', '0004_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 11, 49, 36, 124721, tzinfo=datetime.timezone.utc)),
        ),
    ]
