# Generated by Django 4.2.7 on 2023-12-06 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_blog', '0008_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 19, 9, 43, 270582, tzinfo=datetime.timezone.utc)),
        ),
    ]
