# Generated by Django 5.0.1 on 2024-02-06 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_rename_message_appmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppMessage',
            new_name='Message',
        ),
    ]
